### ISSUE TITLE
OSMC Symbol preview does not work on Firefox

### ISSUE THREAD

**Issue by Talkless** [waymarkedtrails/waymarkedtrails-website#2]
None of osmc:symbol values is rendered in https://hiking.waymarkedtrails.org/osmc_symbols.html
Latest one was `yellow:white:yellow_bar` but the result is just white box.

Firefox developer console prints this:
```
Uncaught (in promise) TypeError: e[2].osmc is undefined
    S OsmcApp.svelte:129
    p OsmcApp.svelte:129
    p OsmcApp.svelte:119
    te index.mjs:1085
    ee index.mjs:1052
    promise callback*he index.mjs:1010
    ctx index.mjs:1868
    se OsmcApp.svelte:60
    s index.mjs:34
    set runtime.esm.js:15
    promise callback*set runtime.esm.js:15
    <anonymous> runtime.esm.js:15
    <anonymous> i18n.js:28
OsmcApp.svelte:129:23
```

Firefox 102.0.1 on Debian Sid. UBlock Origin, NoScript is completely allowed for website.

**Comment by lonvia** [comment]
Works for me with Firefox 102.0.1. Please try a Shift+Reload of the site.

**Comment by Talkless** [comment]
Yep, works now, thanks!
