### ISSUE TITLE
Translation source in titlebar?

### ISSUE THREAD

**Issue by sveinki** [waymarkedtrails/waymarkedtrails-website#6]
While reviewing my translations for Icelandic of the website, I noted that only one titlebar/header/banner of the categories (Winter Sport Slopes) is fully translated, while the others (Hiking, etc) are not, including info like 'Last update' and 'Map data'.
I don't think it's related to late or missing translations.

Any pointers?

**Comment by lonvia** [comment]
It's been a while since I've updated translations on the production server. Better now?

**Comment by sveinki** [comment]
Much better. But I also figured out that at least one of my browsers (Brave) doesn't behave well regarding to the website: I had to select my language for each of the categories/pages, otherwise it stuck to 'Browser default' (guess the support for Icelandic is somewhat broken in Brave).

**Comment by sveinki** [comment]
BTW: The title 'Waymarked Trails' can be considered as a brand name, but is of course also a description of what these maps are about; should it be translated in the top titlebar, and perhaps mention/link to the brand some other place (e.g. in front of 'Map data' or down on the lower bar)?

**Comment by lonvia** [comment]
You have to allow local storage for language settings to work properly. I wouldn't be surprised if there are bugs in the code causing strange behaviour when local storage is blocked. PRs with fixes welcome. ;)

'Waymarked Trails' is indeed a brand name and intentionally not translatable.

Closing as resolved.
